ProductStockTracking.MvcWebUI/Controllers/PhoneController.cs
using ProductStockTracking.Business.Abstract;
using ProductStockTracking.Core.Utilities.Results;
using ProductStockTracking.Entities.Concrete;
using ProductStockTracking.MvcWebUI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductStockTracking.MvcWebUI.Controllers
{
    [Authorize]
    public class PhoneController : Controller
    {

        private readonly IPhoneService _phoneService;
        private readonly IPhoneSaleService _phoneSaleService;

        public PhoneController(IPhoneService phoneService, IPhoneSaleService phoneSaleService)
        {
            _phoneService = phoneService;
            _phoneSaleService = phoneSaleService;
        }
        // GET: Phone
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PhoneList()
        {
            var result = _phoneService.GetList();
            if (result.Success)
                return View(result.Data);
            return View(new List<Phone>());
        }

        [HttpGet]
        public ActionResult AddPhone(int id = 0)
        {
            var result = _phoneService.GetById(id);
            if (result.Success && id != 0)
            {
                return View(result.Data);
            }
            return View(new Phone());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
      
        public ActionResult AddPhone(Phone model)
        {

            // özel validation kullandıysan eğer try catch bas !!!!!!!!!!!!!
            try
            {
                IResult result;
                if (model.Id == 0)
                    result = _phoneService.Add(model);
                else
                    result = _phoneService.Update(model);

                if (result.Success)
                    return RedirectToAction("/PhoneList");

                ViewBag.Message = result.Message;


                return View(model);
            }
            catch (Exception e)
            {

                var a = e.Message.Trim().Replace("\n", " ");

                a =a.Replace("\r", " ");


                ViewBag.Message =a ;


                return View(model); 
            }
            
        }



        public ActionResult AddPhoneSale(string[] phoneSaleModel)
        {

            try
            {

                PhoneSale phoneSale = new PhoneSale();

                phoneSale.PhoneId = Convert.ToInt32(phoneSaleModel[0]);
                phoneSale.Barcode = phoneSaleModel[1];
                phoneSale.NewPhoneOwnersName = phoneSaleModel[2];
                phoneSale.NewPhoneOwnersNo = phoneSaleModel[3];
                phoneSale.DeliveryDate = Convert.ToDateTime(phoneSaleModel[4]);
                phoneSale.DeliveryPrice = Convert.ToInt64(phoneSaleModel[5]);

                var result = _phoneSaleService.Add(phoneSale);

                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(result);
                return Json(resStr);
            }
            catch (Exception)
            {
                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new ErrorResult("Telefon satış bilgilerini gönderirken hata oluştu ! Lütfen bilgileri eksiksiz ve doğru bir şekilde girin."));

                return Json(resStr);
            }

        }

        public ActionResult GetPhoneSaleInfo(int phoneId)
        {
            try
            {
                var result = _phoneSaleService.GetById(phoneId);

                string[] arrayData = { result.Data.Barcode, result.Data.NewPhoneOwnersName, result.Data.NewPhoneOwnersNo.ToString(), result.Data.DeliveryPrice.ToString(), result.Data.DeliveryDate.ToString("dd.MM.yyyy") };

                if (result.Success)
                {
                    var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new SuccessDataResult<string[]>(arrayData));
                    return Json(resStr);
                }

                else
                {
                    var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(result);
                    return Json(resStr);
                }

            }
            catch (Exception)
            {
                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new ErrorResult("Telefon satış kaydı bilgileri gösterirken hata oluştu."));
                return Json(resStr);
            }
        }

    }
}

ProductStockTracking.MvcWebUI/Views/Phone/AddPhone.cshtml
@model ProductStockTracking.Entities.Concrete.Phone
@{
    ViewBag.Title = "AddPhone";
}

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">
       
            @using (Html.BeginForm("AddPhone", "Phone", FormMethod.Post, new { @class = "kt-form", id = "kt-form" }))
            {
                @Html.AntiForgeryToken()


                // <form method="post" action="AddPhone" class="kt-form" id="kt_form">
                <!--begin::Portlet-->
                <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">Telefon Ekle <small>Dikkat !</small></h3>
                        </div>
                        <div class="kt-portlet__head-toolbar">
                            <a href="#" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Back</span>
                            </a>

                            <div class="btn-group">

                                <button type="submit" class="btn btn-brand">

                                    <span class="kt-hidden-mobile">
                                        <i class="la la-check"></i>
                                        Kaydet
                                    </span>

                                </button>


                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__body">

                        <div class="row">
                            <div class="col-xl-2"></div>
                            <div class="col-xl-8">
                                <div class="kt-section kt-section--first">
                                    <div class="kt-section__body">
                                        <h3 class="kt-section__title kt-section__title-lg">Telefon Bilgileri :</h3>
                                        @Html.HiddenFor(model => model.Id)

                                        <div class="form-group row">

                                            <label class="col-3 col-form-label">Barkod</label>
                                            <div class="col-9">
                                                @Html.TextBoxFor(model => model.Barcode, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Barcode, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Marka / Model</label>
                                            <div class="col-9">
                                                @Html.TextBoxFor(model => model.BrandModel, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.BrandModel, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Tür</label>
                                            <div class="col-9">
                                                @Html.EnumDropDownListFor(model => model.PhoneType, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.PhoneType, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Garanti Süresi</label>
                                            <div class="col-9">

                                                @Html.TextBoxFor(model => model.GuaranteeTerm, new { @class = "form-control", type = "number" })
                                                @Html.ValidationMessageFor(model => model.GuaranteeTerm, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-form-label col-lg-3 col-sm-12">Telefon Arızası</label>
                                            <div class="col-9 ">
                                                @Html.TextAreaFor(model => model.FaultDescription, new { @class = "form-control", @rows = "6" })
                                                @Html.ValidationMessageFor(model => model.FaultDescription, "", new { @class = "text-danger" })
                                                <span class="form-text text-muted">Bootstrap maxlength supports textarea as well as inputs</span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-form-label col-lg-3 col-sm-12">Aksesuar Durumu</label>

                                            <div class="col-9 ">
                                                @Html.TextAreaFor(model => model.AccessoryStatus, new { @class = "form-control", @rows = "3" })
                                                @Html.ValidationMessageFor(model => model.AccessoryStatus, "", new { @class = "text-danger" })
                                                <span class="form-text text-muted">Bootstrap maxlength supports textarea as well as inputs</span>
                                            </div>


                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Alış Fiyatı</label>
                                            <div class="col-9">
                                                @Html.TextBoxFor(model => model.ReceivedPrice, new { @class = "form-control", type = "number" })
                                                @Html.ValidationMessageFor(model => model.ReceivedPrice, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="kt-separator kt-separator--border-dashed kt-separator--space-lg"></div>
                                    <div class="kt-section">
                                        <div class="kt-section__body">
                                            <h3 class="kt-section__title kt-section__title-lg">Telefon Sahibi Bilgileri :</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Alınan Kişi Adı</label>
                                                <div class="col-9">
                                                    @Html.TextBoxFor(model => model.OldPhoneOwnersName, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.OldPhoneOwnersName, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Alınan Kişi Numarası</label>
                                                <div class="col-9">
                                                    <div class="input-group">
                                                        <div class="input-group-prepend"><span class="input-group-text"><i class="la la-phone"></i></span></div>

                                                        <input type="text" name="OldPhoneOwnersNo" id="OldPhoneOwnersNo" class="form-control" value="@Model.OldPhoneOwnersNo" placeholder="Phone" aria-describedby="basic-addon1">
                                                    

                                                    </div>
                                                    @Html.ValidationMessageFor(model => model.OldPhoneOwnersNo, "", new { @class = "text-danger" })
                                                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-form-label col-3 ">Alınan Tarih</label>
                                                <div class=" col-9 ">
                                                    @Html.TextBoxFor(model => model.ReceivedDate, new { @class = " form-control", type = "date", @Value = Model.ReceivedDate.ToString("yyyy-MM-dd") })
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-2"></div>
                        </div>

                    </div>
                </div>
                //</form>
            }
            <!--end::Portlet-->
        </div>
    </div>
</div>


@section scripts{






    <script src="~/Scripts/jquery-3.5.0.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @if (ViewBag.Message != null)
    {
        <script>



            function error() {
                swal("İşlem Başarısız!", "@ViewBag.Message", "error");
            }

            error();
        </script>
    }


}