ProductStockTracking.MvcWebUI/Controllers/FaultyPhoneController.cs
using ProductStockTracking.Business.Abstract;
using ProductStockTracking.Core.Utilities.Results;
using ProductStockTracking.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductStockTracking.MvcWebUI.Controllers
{
    [Authorize]

    public class FaultyPhoneController : Controller
    {
        IFaultyPhoneService _faultyPhoneService;
        IFaultyPhoneDeliveryService _faultyPhoneDeliveryService;

        public FaultyPhoneController(IFaultyPhoneService faultyPhoneService, IFaultyPhoneDeliveryService faultyPhoneDeliveryService)
        {
            _faultyPhoneService = faultyPhoneService;
            _faultyPhoneDeliveryService = faultyPhoneDeliveryService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FaultyPhoneList()
        {
            var result = _faultyPhoneService.GetList();
            if (result.Success)
            {
                return View(result.Data);
            }
            return View(new List<FaultyPhone>());
        }

        [HttpGet]
        public ActionResult AddFaultyPhone(int id = 0)
        {
            var result = _faultyPhoneService.GetById(id);
            if (result.Success && id != 0)
            {
                return View(result.Data);
            }
            return View(new FaultyPhone());
        }
        [HttpPost]
        public ActionResult AddFaultyPhone(FaultyPhone model)
        {
            IResult result;
            if (model.Id == 0)           
                result = _faultyPhoneService.Add(model);
            else
                result = _faultyPhoneService.Update(model);
            if (result.Success)
                return RedirectToAction("/FaultyPhoneList");
            
            ViewBag.ErrorMessage = result.Message;


            return View(model);
        }

        public ActionResult AddFaultyPhoneDelivery(string[] faultyPhoneDeliveryModel)
        {

            try
            {
                FaultyPhoneDelivery faultyPhoneDelivery = new FaultyPhoneDelivery();

                faultyPhoneDelivery.FaultyPhoneId = Convert.ToInt32(faultyPhoneDeliveryModel[0]);
                faultyPhoneDelivery.Barcode = faultyPhoneDeliveryModel[1];
                faultyPhoneDelivery.Transactions = faultyPhoneDeliveryModel[2];
                faultyPhoneDelivery.TransactionPrice = Convert.ToInt32(faultyPhoneDeliveryModel[3]);
                faultyPhoneDelivery.DeliveryDate = Convert.ToDateTime(faultyPhoneDeliveryModel[4]);

                var result = _faultyPhoneDeliveryService.Add(faultyPhoneDelivery);

                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(result);
                return Json(resStr);
            }
            catch (Exception)
            {
                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new ErrorResult("Telefon teslim kaydı bilgileri gönderirken hata oluştu ! Lütfen bilgileri eksiksiz ve doğru bir şekilde girin."));

                return Json(resStr);
            }


        }

        public ActionResult GetFaultyPhoneDeliveryInfo(int phoneId)
        {
            try
            {
                var result = _faultyPhoneDeliveryService.GetById(phoneId);
               
                if (result.Success)
                {
                    string[] arrayData = { result.Data.Barcode, result.Data.Transactions, result.Data.TransactionPrice.ToString(), result.Data.DeliveryDate.ToString("dd.MM.yyyy") };

                     var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new SuccessDataResult<string[]>(arrayData));
                    return Json(resStr);
                }
                else
                {
                   var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(result);
                    return Json(resStr);
                }
                 
            }
            catch (Exception)
            {
                var resStr = Newtonsoft.Json.JsonConvert.SerializeObject(new ErrorResult("Telefon teslim kaydı bilgileri gösterirken hata oluştu."));
                return Json(resStr);
            }
        }
    }
}

ProductStockTracking.MvcWebUI/Views/FaultyPhone/AddFaultyPhone.cshtml
@model ProductStockTracking.Entities.Concrete.FaultyPhone
@{
    ViewBag.Title = "AddFaultyPhone";
}

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("AddFaultyPhone", "FaultyPhone", FormMethod.Post, new { @class = "kt-form", id = "kt-form" }))
            {
                <!--begin::Portlet-->
                <div class="kt-portlet kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile" id="kt_page_portlet">
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">Arızalı Telefon Ekle <small>Dikkat !</small></h3>
                        </div>
                        <div class="kt-portlet__head-toolbar">
                            <a href="#" class="btn btn-clean kt-margin-r-10">
                                <i class="la la-arrow-left"></i>
                                <span class="kt-hidden-mobile">Back</span>
                            </a>
                            <div class="btn-group">
                                <button type="submit" class="btn btn-brand">

                                    <span class="kt-hidden-mobile">
                                        <i class="la la-check"></i>
                                        Kaydet
                                    </span>

                                </button>


                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__body">

                        <div class="row">
                            <div class="col-xl-2"></div>
                            <div class="col-xl-8">
                                <div class="kt-section kt-section--first">
                                    <div class="kt-section__body">
                                        <h3 class="kt-section__title kt-section__title-lg">Telefon Bilgileri :</h3>
                                        <div class="form-group row">
                                            @Html.HiddenFor(model => model.Id)
                                            <label class="col-3 col-form-label">Barkod</label>
                                            <div class="col-9">
                                                @Html.TextBoxFor(model => model.Barcode, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Barcode, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-3 col-form-label">Marka / Model</label>
                                            <div class="col-9">
                                                @Html.TextBoxFor(model => model.BrandModel, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.BrandModel, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-form-label col-lg-3 col-sm-12">Telefon Arızası</label>
                                            <div class="col-9 ">
                                                @Html.TextAreaFor(model => model.FaultDescription, new { @class = "form-control", @rows = "6" })
                                                @Html.ValidationMessageFor(model => model.FaultDescription, "", new { @class = "text-danger" })

                                                <span class="form-text text-muted">Bootstrap maxlength supports textarea as well as inputs</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="kt-separator kt-separator--border-dashed kt-separator--space-lg"></div>
                                    <div class="kt-section">
                                        <div class="kt-section__body">
                                            <h3 class="kt-section__title kt-section__title-lg">Telefon Sahibi Bilgileri :</h3>
                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Telefon Sahibinin Adı</label>
                                                <div class="col-9">
                                                    @Html.TextBoxFor(model => model.PhoneOwnersName, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.PhoneOwnersName, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group row">
                                                <label class="col-3 col-form-label">Telefon Sahibinin Numarası</label>
                                                <div class="col-9">
                                                    <div class="input-group">
                                                        <div class="input-group-prepend"><span class="input-group-text"><i class="la la-phone"></i></span></div>

                                                        <input type="text" name="PhoneOwnersNo" id="PhoneOwnersNo" class="form-control" value="@Model.PhoneOwnersNo" placeholder="Phone" aria-describedby="basic-addon1">
                                                        @Html.ValidationMessageFor(model => model.PhoneOwnersNo, "", new { @class = "text-danger" })
                                                    </div>
                                                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-form-label col-3 ">Alınan Tarih</label>
                                                <div class=" col-9 ">

                                                    @Html.TextBoxFor(model => model.ReceivedDate, new { @class = " form-control", type = "date", @Value = Model.ReceivedDate.ToString("yyyy-MM-dd") })
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-2"></div>
                        </div>

                    </div>
                </div>

            }
            <!--end::Portlet-->
        </div>
    </div>
</div>


@section scripts{



    @if (ViewBag.ErrorMessage != null)
    {
        <script>
            function message() {
                swal("İşlem Başarısız!", "@ViewBag.ErrorMessage", "error");

            }
            message();


        </script>
    }

    else
    {
        <script>

            function message() {

            }

            message();


        </script>
    }


    <script src="~/Scripts/jquery-3.5.0.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}